#!/bin/sh
# Stage 4 (Box @@N@@): clone the proven Box 1 base image and apply the Box-@@N@@
# inject (no reinstall).  Stage payload into a tar, hand it to the guest as a raw
# disk, and let inject@@N@@-guest.sh (root, inside) do the planting.
set -eu
export BOX_ENV_FILE=box@@N@@.env
export BOX_PAYLOAD_SUBDIR=payloads@@N@@
. "$(dirname "$0")/lib.sh"

need openssl
BASE="$REPO_ROOT/${BOX@@N@@_BASE_IMAGE:?set BOX@@N@@_BASE_IMAGE in box@@N@@.env}"
[ -f "$BASE" ] || die "no base image $BASE (build Box 1 first: make build)"

mkdirs
log "cloning base $BASE -> $IMAGE"
cp "$BASE" "$IMAGE"

REAL_FLAG=$(sh "$REPO_ROOT/build/flag.sh") || die "could not derive flag (set BOX_FLAG_SEED or secret/flag.seed)"

STAGE="$WORK_DIR/inject@@N@@-stage"
TAR="$WORK_DIR/inject@@N@@-payload.tar"
rm -rf "$STAGE"; mkdir -p "$STAGE/files"

cat > "$STAGE/box-guest.env" <<EOF
# generated by build/40-inject@@N@@.sh — do not edit
FOOTHOLD_USER="$BOX_FOOTHOLD_USER"
TRUST_USER="$BOX_TRUST_USER"
HOSTNAME_FQDN="$BOX_HOSTNAME.$BOX_DOMAIN"
LOOT_DIR="$BOX_LOOT_DIR"
FLAG_REAL='$REAL_FLAG'
FLAG_DECOY='$BOX_FLAG_DECOY'
# TODO: add any other vars inject@@N@@-guest.sh reads
EOF

cp "$PAYLOAD_DIR/inject@@N@@-guest.sh" "$STAGE/RUN.sh"
# TODO: cp your other payload files into "$STAGE" / "$STAGE/files"

log "packing payload tar"
( cd "$STAGE" && tar cf "$TAR" . )
ok "payload tar: $TAR ($(wc -c < "$TAR") bytes)"

PY="python3"; [ -x "$REPO_ROOT/.venv/bin/python3" ] && PY="$REPO_ROOT/.venv/bin/python3"
"$PY" -c 'import pexpect' 2>/dev/null || die "pexpect missing (run: make deps)"
export BOX_IMAGE_ABS="$IMAGE"
export BOX_PAYLOAD_TAR="$TAR"
export BOX_SERIAL_LOG="$WORK_DIR/inject@@N@@-serial.log"
export QEMU_BIN BOX_MACHINE BOX_CPU BOX_MEM_MB BOX_ROOT_PASS
log "driving guest inject session (slow: full multiuser boot under TCG)"
"$PY" "$REPO_ROOT/build/drive_guest.py" || die "guest inject session failed (see $BOX_SERIAL_LOG)"
ok "Box @@N@@ inject complete -> $IMAGE"
